name: syncly_flutter
description: A Flutter plugin for seamless offline data synchronization with local storage and conflict handling.
version: 0.0.2
homepage: https://sufiyanrazaq.com/
repository: https://github.com/SufiyanRazaq/syncly_flutter

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  plugin_platform_interface: ^2.0.2
  connectivity_plus: ^6.1.3
  path_provider: ^2.1.5
  sqflite: ^2.3.3+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.example.syncly_flutter
        pluginClass: SynclyFlutterPlugin
      ios:
        pluginClass: SynclyFlutterPlugin
      macos:
        pluginClass: SynclyFlutterPlugin
