name: syncly_flutter
description: "A Flutter package for offline-first data storage and seamless synchronization. Automatically saves data locally and syncs it with the server when the device reconnects to the internet, featuring customizable conflict resolution strategies."
version: 0.0.1
homepage: https://sufiyanrazaq.com/
repository: https://github.com/SufiyanRazaq/syncly_flutter


environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2
  connectivity_plus: ^6.1.3
  path_provider: ^2.1.5
  sqflite: ^2.3.3+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.example.syncly_flutter
        pluginClass: SynclyFlutterPlugin
      ios:
        pluginClass: SynclyFlutterPlugin
      linux:
        pluginClass: SynclyFlutterPlugin
      macos:
        pluginClass: SynclyFlutterPlugin
      windows:
        pluginClass: SynclyFlutterPluginCApi
      web:
        pluginClass: SynclyFlutterWeb
        fileName: syncly_flutter_web.dart
